import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ChevronDown, Facebook, Instagram, Linkedin, Mail, MapPin, Menu, MessageCircle, Search, SlidersHorizontal, Youtube } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { cities, faqs, fields, INSTITUTE, partners, sessions, testimonials } from "@/data/site";
import workshop from "@/assets/photos/workshop.webp";
import participant from "@/assets/photos/participant.webp";
import nairobi from "@/assets/photos/nairobi.webp";
import meeting from "@/assets/photos/meeting.webp";
import whiteboard from "@/assets/photos/whiteboard.webp";
import classroom from "@/assets/photos/classroom.webp";
import team from "@/assets/photos/team.webp";
import online from "@/assets/photos/online.webp";
import portraitA from "@/assets/photos/portrait-a.webp";
import portraitB from "@/assets/photos/portrait-b.webp";
import portraitC from "@/assets/photos/portrait-c.webp";

const photos: Record<string, string> = { workshop, participant, nairobi, meeting, whiteboard, classroom, team, online, "portrait-a": portraitA, "portrait-b": portraitB, "portrait-c": portraitC };
const internal = "/?browse=all";
const footerGroups = [
  { title: "Fields of study", links: fields.map((field) => field.name) },
  { title: "Company", links: ["About", "Trainers", "Accreditation", "Gallery", "Careers", "Blog"] },
  { title: "Help", links: ["Calendar", "Payments", "Visa support", "Terms", "Privacy"] },
];

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Professional short courses across Africa | Geovani Capital Training" },
    { name: "description", content: "Compare dates, cities, formats and prices for 640 instructor-led professional courses in Africa and live online." },
    { property: "og:title", content: "Geovani Capital Training — practical professional training" },
    { property: "og:description", content: "Short instructor-led courses for professionals, teams and institutions across Africa." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: HomePage,
});

function Logo() {
  return <Link to="/" aria-label="Geovani Capital Training home" className="inline-flex items-center gap-2.5 leading-none"><SunMark /><span className="flex flex-col"><span className="font-display text-[1.35rem] font-semibold sm:text-2xl">Geovani Capital</span><span className="mt-1 text-[0.7rem] font-bold uppercase tracking-[0.22em] opacity-70">Training</span></span></Link>;
}
function SunMark() {
  return <svg aria-hidden="true" viewBox="0 0 34 22" className="h-6 w-8 shrink-0 text-gold"><path d="M3 20a14 14 0 0 1 28 0" fill="currentColor"/><path d="M17 1v5M4 9l4 3M30 9l-4 3" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
}
function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <>
    <a href="#main" className="fixed left-4 top-2 z-[100] -translate-y-20 bg-accent px-4 py-2 text-accent-foreground focus:translate-y-0">Skip to content</a>
    <div className="bg-foreground text-background text-xs"><div className="mx-auto flex h-9 max-w-7xl items-center justify-between px-4 lg:px-6"><Link to="/" search={{ intake: "october" }}>Next intake: 13 Oct · Nairobi & Online</Link><div className="hidden items-center gap-5 sm:flex"><a href={`tel:${INSTITUTE.phoneHref}`}>{INSTITUTE.phone}</a><a href="https://wa.me/254700000000">WhatsApp</a><a href={`mailto:${INSTITUTE.email}`}>{INSTITUTE.email}</a></div><a aria-label="Chat with Geovani Capital Training on WhatsApp" className="sm:hidden" href="https://wa.me/254700000000"><MessageCircle className="size-5"/></a></div></div>
    <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur-sm"><div className="mx-auto flex h-[74px] max-w-7xl items-center justify-between gap-5 px-4 lg:px-6"><Logo/>
      <nav aria-label="Main navigation" className="hidden items-center gap-5 lg:flex">
        <div className="group relative"><button aria-haspopup="true" className="flex h-11 items-center gap-1 font-medium">Courses <ChevronDown className="size-4"/></button><div className="invisible absolute left-1/2 top-full w-[760px] -translate-x-1/2 pt-3 opacity-0 transition group-focus-within:visible group-focus-within:opacity-100 group-hover:visible group-hover:opacity-100"><div className="grid grid-cols-[1fr_1fr_1.1fr] gap-6 border bg-background p-6 shadow-xl"><div className="col-span-2 grid grid-cols-2 gap-x-5">{fields.map(f=><Link key={f.name} to="/" search={{ field:f.name }} className="border-b py-3 text-sm font-medium hover:text-primary">{f.name}</Link>)}</div><div className="border-l pl-6"><p className="mb-3 text-xs font-bold uppercase text-muted-foreground">Most booked</p><Link to="/" search={{ course:"m-e" }} className="block py-2 text-sm">M&E for development programmes</Link><Link to="/" search={{ course:"power-bi" }} className="block py-2 text-sm">Data analysis with Power BI</Link><img src={whiteboard} alt="Facilitator leading a practical whiteboard session" width="320" height="180" className="mt-3 h-24 w-full object-cover"/></div></div></div></div>
        {["Calendar","Cities","In-house training","About"].map(x=><Link key={x} to="/" search={{ page:x.toLowerCase().replaceAll(" ","-") }} className="font-medium hover:text-primary">{x}</Link>)}
      </nav>
      <div className="hidden items-center gap-2 lg:flex"><Button variant="ghost" size="icon" aria-label="Search courses"><Search/></Button><Button variant="outline" asChild><Link to="/" search={{ advisor:true }}>Talk to an advisor</Link></Button><Button asChild><Link to="/" search={{ browse:"all" }}>Browse courses</Link></Button></div>
      <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu"><Menu/></Button></SheetTrigger><SheetContent side="right" className="w-full max-w-none overflow-y-auto sm:max-w-none"><SheetHeader><SheetTitle className="text-left font-display text-3xl">Courses</SheetTitle><SheetDescription className="sr-only">Browse fields and contact Geovani Capital Training</SheetDescription></SheetHeader><label className="mt-8 flex h-12 items-center gap-3 border px-3"><Search className="size-5"/><span className="sr-only">Search courses</span><input className="min-w-0 flex-1 bg-transparent outline-none" placeholder="What do you want to learn?"/></label><nav className="mt-6">{fields.map(f=><Link onClick={()=>setMenuOpen(false)} key={f.name} to="/" search={{ field:f.name }} className="flex min-h-14 items-center justify-between border-b text-lg font-medium">{f.name}<ArrowRight className="size-4"/></Link>)}</nav><div className="mt-8 grid gap-2"><a className="min-h-11" href={`tel:${INSTITUTE.phoneHref}`}>{INSTITUTE.phone}</a><a className="min-h-11" href={`mailto:${INSTITUTE.email}`}>{INSTITUTE.email}</a><a className="min-h-11" href="https://wa.me/254700000000">WhatsApp</a></div></SheetContent></Sheet>
    </div></header>
  </>;
}
function SearchPanel() {
  return <form onSubmit={e=>e.preventDefault()} className="mt-8 border bg-background p-2 shadow-[0_12px_36px_color-mix(in_oklab,var(--foreground)_8%,transparent)]"><div className="flex min-h-12 items-center gap-3 px-3"><Search className="size-5 text-primary"/><label htmlFor="course-search" className="sr-only">What do you want to learn?</label><input id="course-search" className="min-w-0 flex-1 bg-transparent outline-none" placeholder="What do you want to learn?"/><Sheet><SheetTrigger asChild><Button type="button" variant="outline" className="md:hidden"><SlidersHorizontal/> Filters</Button></SheetTrigger><SheetContent side="bottom" className="rounded-t-2xl"><SheetHeader><SheetTitle className="text-left font-display text-2xl">Search filters</SheetTitle><SheetDescription className="text-left">Choose where and how you want to learn.</SheetDescription></SheetHeader><div className="mt-5 grid gap-4">{["City","Format","Month"].map(x=><label key={x} className="grid gap-1 text-sm font-bold">{x}<select className="h-12 border bg-background px-3 font-normal"><option>Any {x.toLowerCase()}</option></select></label>)}<Button>Apply filters</Button></div></SheetContent></Sheet></div><div className="hidden border-t md:grid md:grid-cols-[1fr_1fr_1fr_auto]">{["City","Format","Month"].map(x=><label key={x} className="border-r"><span className="sr-only">{x}</span><select className="h-12 w-full bg-transparent px-3 text-sm font-medium"><option>Any {x.toLowerCase()}</option></select></label>)}<Button className="h-12 rounded-none px-7"><Search/> Search</Button></div></form>;
}
function Hero() {
  return <section className="relative overflow-hidden pb-16 pt-12 lg:pb-24 lg:pt-20"><div className="dot-pattern absolute inset-y-0 left-0 w-1/5 opacity-30"/><div className="relative mx-auto grid max-w-7xl gap-14 px-4 lg:grid-cols-[1.06fr_.94fr] lg:px-6"><div className="self-center"><p className="mb-5 inline-flex rounded-full border px-4 py-1.5 text-sm font-bold text-primary">Short courses for working professionals</p><h1 className="max-w-3xl text-balance text-[clamp(2.75rem,6vw,5rem)] font-medium leading-[.98]">Practical training, taught by people who’ve <span className="relative whitespace-nowrap italic">done the work<svg aria-hidden="true" viewBox="0 0 320 18" className="absolute -bottom-2 left-0 h-4 w-full text-gold"><path d="M3 11c54-8 101 5 157-2 51-7 94-1 157-4" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round"/></svg></span>.</h1><p className="mt-7 max-w-[52ch] text-lg text-muted-foreground">5–10 day courses in eight African cities and live online. Built for NGOs, public institutions and finance teams.</p><SearchPanel/><div className="mt-4 flex flex-wrap gap-2 text-sm"><span className="py-2 text-muted-foreground">Popular:</span>{["Monitoring & Evaluation","Power BI","Procurement","Data Protection","Leadership"].map(x=><Link to="/" search={{ q:x }} key={x} className="rounded-full border px-3 py-2 hover:border-primary hover:text-primary">{x}</Link>)}</div></div>
    <div className="relative mx-auto min-h-[520px] w-full max-w-[580px]"><div className="absolute left-[12%] top-[12%] size-[70%] rounded-full bg-secondary"/><img src={workshop} alt="African professionals working through a practical workshop" width="900" height="1200" fetchPriority="high" className="arch absolute left-0 top-0 h-[440px] w-[55%] object-cover"/><img src={participant} alt="Participant listening during an instructor-led session" width="600" height="600" className="absolute right-[3%] top-[4%] aspect-square w-[37%] rounded-full border-[10px] border-background object-cover"/><img src={nairobi} alt="Nairobi skyline at dusk" width="900" height="500" className="absolute bottom-3 right-0 h-[170px] w-[47%] rounded-full border-[8px] border-background object-cover"/><div className="ticket-notch absolute bottom-8 left-[8%] grid w-[min(400px,86%)] grid-cols-[70px_1fr] bg-background shadow-xl"><div className="flex flex-col items-center justify-center bg-accent p-3 text-accent-foreground"><strong className="font-display text-3xl tabular">13</strong><span className="text-xs font-bold uppercase">Oct</span></div><div className="border-l border-dashed p-4"><p className="text-xs font-bold text-primary">Starts Mon · Nairobi</p><p className="mt-1 font-display text-lg font-semibold leading-tight">M&E for development programmes</p><p className="mt-2 text-xs text-muted-foreground">10 days · USD 2,450</p></div></div></div></div></section>;
}
function TrustStrip() { const logos=[...partners,...partners]; return <section aria-label="Partner organisations" className="border-y py-6"><div className="mx-auto flex max-w-7xl items-center gap-6 overflow-hidden px-4"><p className="w-24 shrink-0 text-xs font-bold uppercase text-muted-foreground">Trusted by teams at</p><div className="hidden min-w-0 overflow-hidden sm:block"><div className="marquee-track flex w-max hover:[animation-play-state:paused]">{logos.map((p,i)=><span aria-hidden={i>=partners.length} key={`${p}-${i}`} className="flex w-52 shrink-0 items-center justify-center border-l px-6 text-center font-display text-sm font-semibold text-muted-foreground grayscale">{p}</span>)}</div></div><div className="grid flex-1 grid-cols-2 gap-3 sm:hidden">{partners.slice(0,4).map(p=><span key={p} className="text-xs font-semibold text-muted-foreground">{p}</span>)}</div></div></section> }
function SessionList() {
 const [city,setCity]=useState("All"); const filtered=sessions.filter(s=>city==="All"||s.city===city).slice(0,6);
 return <section className="py-16 lg:py-24"><div className="mx-auto max-w-7xl px-4 lg:px-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-bold uppercase text-primary">Course calendar</p><h2 className="text-4xl leading-tight md:text-6xl">Starting in the next 30 days</h2></div><Link to="/" search={{ calendar:"2026-27" }} className="font-bold text-primary underline">Full 2026–27 calendar →</Link></div><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{["All","Nairobi","Kigali","Online","Dubai"].map(c=><Button key={c} variant={city===c?"default":"outline"} className="rounded-full" onClick={()=>setCity(c)}>{c}</Button>)}</div><div className="mt-6 border-t">{filtered.map((s,i)=><article key={s.title} className="grid gap-4 border-b py-5 md:grid-cols-[92px_1.5fr_1fr_1fr_auto] md:items-center"><div className={`flex h-20 w-20 flex-col items-center justify-center ${i===0&&city==="All"?"bg-accent text-accent-foreground":"bg-secondary"}`}><strong className="font-display text-4xl leading-none tabular">{s.date}</strong><span className="text-xs font-bold uppercase">{s.month}</span></div><div><span className="text-xs font-bold uppercase text-primary">{s.field}</span><h3 className="mt-1 text-xl font-semibold leading-tight">{s.title}</h3></div><div className="text-sm"><p className="flex items-center gap-2 font-bold"><MapPin className="size-4 text-gold-text"/>{s.city}</p><p className="mt-1 text-muted-foreground">{s.format} · {s.duration}</p></div><div className="text-sm tabular">{s.classroom&&<p>Classroom <strong>USD {s.classroom.toLocaleString()}</strong></p>}{s.online&&<p>Online <strong>USD {s.online.toLocaleString()}</strong></p>}{s.seats&&s.seats<6&&<p className="mt-1 font-bold text-gold-text">{s.seats} seats left</p>}</div><Button variant="outline" asChild><Link to="/" search={{ course:s.title }}>View & book</Link></Button></article>)}</div>{filtered.length===0&&<p className="border-b py-10 text-muted-foreground">No sessions in this filter. View the full calendar for more dates.</p>}</div></section>;
}
function Fields() { return <section className="relative overflow-hidden bg-secondary py-16 lg:py-24"><div className="absolute -right-24 top-20 size-80 rounded-full border-[55px] border-gold opacity-25"/><div className="relative mx-auto max-w-7xl px-4 lg:px-6"><p className="text-sm font-bold uppercase text-primary">Browse by field</p><h2 className="mt-3 max-w-4xl text-4xl leading-tight md:text-6xl">Eight fields. {INSTITUTE.courseCount} courses. One place to start.</h2><div className="mt-10 grid auto-rows-[180px] grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{fields.map((f,i)=><Link to="/" search={{ field:f.name }} key={f.name} className={`group relative overflow-hidden border bg-background p-5 ${i===0?"col-span-2 row-span-2":i===1?"row-span-2":i===2?"col-span-2":""}`}><img src={[workshop,whiteboard,meeting,team,classroom,online,nairobi,participant][i]} alt={`${f.name} professional training`} width="900" height="600" loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-[linear-gradient(0deg,var(--foreground),transparent_78%)] opacity-80"/><div className="absolute inset-x-0 bottom-0 p-5 text-background"><span className="text-xs font-bold uppercase">{f.count} courses</span><h3 className="mt-1 text-xl font-semibold leading-tight md:text-2xl">{f.name}</h3>{i<3&&<p className="mt-2 hidden text-xs opacity-80 md:block">{f.examples.join(" · ")}</p>}<ArrowRight className="absolute bottom-5 right-5 size-5 transition group-hover:translate-x-1"/></div></Link>)}</div></div></section> }
const formats=[
 {name:"Classroom",image:classroom,shape:"arch",facts:["8 cities","20 participants max","Airport pickup and hotel booking help"],price:"USD 1,250–2,850"},
 {name:"Live online",image:online,shape:"rounded-full",facts:["Live on Zoom, not recorded","Same trainers","EAT and WAT friendly hours"],price:"USD 650–1,250"},
 {name:"In-house for teams",image:team,shape:"rounded-md",facts:["Built around your team’s roles","From 8 participants","Delivered at your office or ours"],price:"Quoted by group size"},
];
function FormatContent({i}:{i:number}) { const f=formats[i]; return <div className="grid items-center gap-8 md:grid-cols-[1.2fr_1fr]"><img src={f.image} alt={`${f.name} professional training session`} width="1000" height="700" loading="lazy" className={`${f.shape} h-[330px] w-full object-cover md:h-[440px]`}/><div><h3 className="text-4xl">{f.name}</h3><ul className="mt-6 space-y-3">{f.facts.map(x=><li key={x} className="flex gap-3 border-b pb-3"><span aria-hidden="true" className="text-gold">●</span>{x}</li>)}</ul><p className="mt-6 text-sm text-muted-foreground">Typical price</p><p className="font-display text-2xl tabular">{f.price}</p><Button className="mt-6" asChild><Link to="/" search={{ format:f.name }}>Browse {f.name.toLowerCase()}</Link></Button></div></div> }
function Formats() { const [active,setActive]=useState(0); return <section className="py-16 lg:py-28"><div className="mx-auto max-w-7xl px-4 lg:px-6"><p className="text-sm font-bold uppercase text-primary">Choose your format</p><h2 className="mt-3 max-w-2xl text-4xl md:text-6xl">The same practical standard, three ways.</h2><div className="mt-10 hidden grid-cols-[270px_1fr] gap-12 md:grid"><div role="tablist" aria-label="Training formats" className="border-t">{formats.map((f,i)=><button role="tab" aria-selected={active===i} onClick={()=>setActive(i)} key={f.name} className={`flex min-h-16 w-full items-center justify-between border-b text-left font-bold ${active===i?"text-primary":"text-muted-foreground"}`}>{f.name}<ArrowRight className="size-4"/></button>)}</div><div role="tabpanel"><FormatContent i={active}/></div></div><Accordion type="single" collapsible defaultValue="format-0" className="mt-8 md:hidden">{formats.map((f,i)=><AccordionItem value={`format-${i}`} key={f.name}><AccordionTrigger className="text-lg">{f.name}</AccordionTrigger><AccordionContent><FormatContent i={i}/></AccordionContent></AccordionItem>)}</Accordion></div></section> }
function Proof() { const stats=[[INSTITUTE.rating,`average from ${INSTITUTE.reviewCount} published reviews`],[INSTITUTE.trainerCount,"approved trainers, all practitioners"],[INSTITUTE.cityCount,"classroom cities"],[INSTITUTE.professionalsTrained,"professionals trained since 2019"]]; return <section className="arc-pattern bg-foreground py-16 text-background lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-2 lg:px-6"><h2 className="max-w-md text-5xl leading-tight md:text-7xl">We publish our numbers.</h2><div className="grid grid-cols-2 border-l border-t border-background/20">{stats.map(([n,t])=><div key={t} className="border-b border-r border-background/20 p-5 md:p-8"><strong className="font-display text-4xl text-gold tabular md:text-6xl">{n}</strong><p className="mt-3 max-w-[18ch] text-sm text-background/75">{t}</p></div>)}</div></div></section> }
function Cities() { const rail=useRef<HTMLDivElement>(null); const move=(n:number)=>rail.current?.scrollBy({left:n*320,behavior:"smooth"}); return <section className="py-16 lg:py-24"><div className="mx-auto max-w-7xl px-4 lg:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase text-primary">Classroom cities</p><h2 className="mt-3 text-4xl md:text-6xl">Train somewhere worth travelling to</h2></div><div className="hidden gap-2 md:flex"><Button variant="outline" size="icon" aria-label="Previous cities" onClick={()=>move(-1)}><ArrowLeft/></Button><Button variant="outline" size="icon" aria-label="Next cities" onClick={()=>move(1)}><ArrowRight/></Button></div></div><div ref={rail} className="mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto pb-5">{cities.map((c,i)=><article key={c.name} className="w-[260px] shrink-0 snap-start md:w-[300px]"><div className="relative h-[420px] overflow-hidden rounded-full"><img src={photos[c.image]} alt={`Training destination in ${c.name}, ${c.country}`} width="700" height="1000" loading="lazy" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(0deg,var(--foreground),transparent_60%)]"/><div className="absolute inset-x-0 bottom-10 text-center text-background"><h3 className="text-3xl">{c.name}</h3><p className="text-sm">{c.country} · {c.sessions} upcoming</p></div></div><Link to="/" search={{ city:c.name }} className="mt-4 flex min-h-11 items-center justify-center font-bold text-primary underline">View {c.name} sessions</Link>{i===0&&<p className="mt-2 text-center text-xs text-muted-foreground">Visa, airport transfer and accommodation support included for international participants.</p>}</article>)}</div><p className="text-xs text-muted-foreground md:hidden">Swipe to explore all eight cities →</p></div></section> }
function Testimonials() { const shown=testimonials.slice(0,3); return <section className="bg-secondary py-16 lg:py-24"><div className="mx-auto max-w-7xl px-4 lg:px-6"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase text-primary">Participant reviews</p><h2 className="mt-3 text-4xl md:text-6xl">What changed after class</h2></div><Link to="/" search={{ reviews:"all" }} className="hidden font-bold text-primary underline md:block">Read all {INSTITUTE.reviewCount} reviews →</Link></div><div className="mt-10 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><article className="relative border bg-background p-7 md:p-12"><span aria-hidden="true" className="absolute right-7 top-0 font-display text-9xl leading-none text-gold/40">“</span><blockquote className="relative font-display text-3xl leading-snug">“{shown[0].quote}”</blockquote><Person t={shown[0]}/></article><div className="grid gap-5">{shown.slice(1).map(t=><article key={t.name} className="border-l-4 border-accent bg-background p-6"><blockquote className="font-display text-xl leading-snug">“{t.quote}”</blockquote><Person t={t}/></article>)}</div></div><Link to="/" search={{ reviews:"all" }} className="mt-6 block font-bold text-primary underline md:hidden">Read all {INSTITUTE.reviewCount} reviews →</Link></div></section> }
function Person({t}:{t:(typeof testimonials)[number]}) { return <div className="mt-6 flex items-center gap-3"><img src={photos[t.image]} alt={`Portrait of ${t.name}`} width="96" height="96" loading="lazy" className="size-12 rounded-full object-cover"/><div><p className="font-bold">{t.name} · {t.role}</p><p className="text-xs text-muted-foreground">{t.org} · {t.course}</p></div></div> }
function Teams() { return <section className="relative overflow-hidden bg-primary py-16 text-primary-foreground lg:py-20"><div className="absolute -bottom-40 -right-28 size-96 rounded-full bg-gold"/><div className="relative mx-auto max-w-7xl px-4 lg:px-6"><h2 className="text-4xl md:text-6xl">Training a whole team?</h2><p className="mt-4 max-w-2xl text-lg text-primary-foreground/80">Tell us the roles and the outcome you need. We’ll propose a programme, trainer and dates within two working days.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button variant="gold" asChild><Link to="/" search={{ team:true }}>Plan team training</Link></Button><Button variant="outline" className="border-primary-foreground bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-primary" asChild><a href="data:application/pdf,%25PDF-1.4%0A%25%20Geovani%20Capital%20Training%202026-27%20Calendar" download="geovani-capital-training-2026-27-calendar.pdf">Download 2026–27 calendar (PDF)</a></Button></div></div></section> }
function FAQ() { return <section className="py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-4 lg:grid-cols-[.75fr_1.25fr] lg:px-6"><div><p className="text-sm font-bold uppercase text-primary">Good to know</p><h2 className="mt-3 text-5xl">Questions before you book</h2></div><Accordion type="single" collapsible>{faqs.map((f,i)=><AccordionItem key={f.q} value={`faq-${i}`}><AccordionTrigger className="min-h-16 text-left text-base">{f.q}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 text-base text-muted-foreground">{f.a}</AccordionContent></AccordionItem>)}</Accordion></div></section> }
function Newsletter() { const [sent,setSent]=useState(false); return <section className="bg-secondary py-12"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-4 md:flex-row md:items-center lg:px-6"><div><h2 className="text-3xl">Stay close to the calendar</h2><p className="mt-1 text-muted-foreground">One email a month: new dates and course changes. No spam.</p></div>{sent?<p role="status" className="border-l-4 border-primary pl-4 font-bold text-primary">You’re subscribed. Watch your inbox for the next calendar note.</p>:<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="flex w-full max-w-lg flex-col gap-2 sm:flex-row"><label htmlFor="newsletter" className="sr-only">Work email</label><input id="newsletter" required type="email" className="h-12 min-w-0 flex-1 border bg-background px-4" placeholder="Your work email"/><Button type="submit">Subscribe</Button></form>}</div></section> }
function Footer() { return <footer className="bg-foreground py-16 text-background"><div className="mx-auto max-w-7xl px-4 lg:px-6"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><Logo/><p className="mt-5 max-w-xs text-sm text-background/70">Practical short courses for professionals and institutional teams across Africa.</p><address className="mt-5 text-sm not-italic text-background/70">Westlands, Nairobi, Kenya<br/><a href={`tel:${INSTITUTE.phoneHref}`}>{INSTITUTE.phone}</a><br/><a href={`mailto:${INSTITUTE.email}`}>{INSTITUTE.email}</a></address></div>{footerGroups.map(g=><div key={g.title}><h3 className="font-sans text-sm font-bold uppercase text-gold">{g.title}</h3><ul className="mt-4 space-y-2">{g.links.map(x=><li key={x}><Link to="/" search={{ page:x.toLowerCase().replaceAll(" ","-") }} className="text-sm text-background/70 hover:text-gold">{x}</Link></li>)}</ul></div>)}</div><div className="mt-12 flex flex-col justify-between gap-5 border-t border-background/20 pt-6 text-xs text-background/60 sm:flex-row sm:items-center"><p>© 2026 Geovani Capital Training. All rights reserved.</p><div className="flex gap-2">{[[Linkedin,"LinkedIn"],[Facebook,"Facebook"],[Instagram,"Instagram"],[Youtube,"YouTube"]].map(([Icon,label])=><a key={String(label)} href={`https://${String(label).toLowerCase()}.com`} aria-label={`Geovani Capital Training on ${label}`} className="flex size-11 items-center justify-center rounded-full border border-background/30"><Icon className="size-4"/></a>)}</div></div></div></footer> }
function FloatingActions() { const [show,setShow]=useState(false); useEffect(()=>{const el=document.querySelector("#hero-search-anchor"); if(!el)return; const obs=new IntersectionObserver(([entry])=>setShow(!entry.isIntersecting));obs.observe(el);return()=>obs.disconnect()},[]); return <><a href="https://wa.me/254700000000" aria-label="Chat with Geovani Capital Training on WhatsApp" className="fixed bottom-20 right-4 z-40 flex size-12 items-center justify-center rounded-full bg-gold text-primary shadow-lg md:bottom-5"><MessageCircle/></a><div className={`fixed inset-x-0 bottom-0 z-30 border-t bg-background p-2 transition md:hidden ${show?"translate-y-0":"translate-y-full"}`}><Button className="w-full" asChild><Link to="/" search={{ browse:"all" }}>Browse courses</Link></Button></div></> }
function HomePage() { return <div className="min-h-screen bg-background text-foreground"><Header/><main id="main"><div id="hero-search-anchor"><Hero/></div><TrustStrip/><SessionList/><Fields/><Formats/><Proof/><Cities/><Testimonials/><Teams/><FAQ/><Newsletter/></main><Footer/><FloatingActions/></div> }
